export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const FAVORITE_ROUTE = '/favorites'
export const CATEGORY_ROUTE = '/category'
